### ISSUE TITLE
documentation / actions implementation

### ISSUE THREAD

**Issue by conal-mediro** [dlopes7/dynatrace-openkit-python#1]
I would like to integrate openkit sdk with an existing python app and came across your code.
I see it connects, but most methods aren't implemented yet.
Are there plans to continue development in the short term?

**Comment by dlopes7** [comment]
Hello, not in the short term, pull requests are welcome

**Comment by conal-mediro** [comment]
Hi, I would like to have a go at implementing if this approach ends up viable. Will submit a PR if I make decent progress, thank you.

**Comment by conal-mediro** [comment]
Think I'll close this then, thanks for merging.
